0x3:
    bExp: 0
    entityID: 7
    entityInstance: 7
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/SCM_TEMP
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
0xE:
    bExp: 0
    entityID: 10
    entityInstance: 1
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 51
    offsetB: 0
    path: /xyz/openbmc_project/sensors/power/HSC0_PIN
    rExp: -1
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 8
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Watts
0xF:
    bExp: 5
    entityID: 10
    entityInstance: 2
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 196
    offsetB: 1
    path: /xyz/openbmc_project/sensors/voltage/HSC0_VIN
    rExp: -4
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
0x10:
    bExp: 0
    entityID: 10
    entityInstance: 3
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 51
    offsetB: 0
    path: /xyz/openbmc_project/sensors/current/HSC0_IOUT
    rExp: -2
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 3
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Amperes
0x14:
    bExp: 0
    entityID: 10
    entityInstance: 4
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/HSC0_TEMP
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC


0x1D:
    bExp: 0
    entityID: 3
    entityInstance: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/discrete/temperature/CPU_THERMAL_TRIP
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 3
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC



0x1E:
    bExp: 0
    entityID: 3
    entityInstance: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/discrete/temperature/PCH_THERMAL_TRIP
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 3
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC







0x72:
    bExp: 0
    entityID: 7
    entityInstance: 1
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/TEMP_INLET_38
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
0x73:
    bExp: 0
    entityID: 7
    entityInstance: 2
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/TEMP_INLET_3A
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
0x74:
    bExp: 0
    entityID: 7
    entityInstance: 3
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/TEMP_INLET_3C
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
0x75:
    bExp: 0
    entityID: 7
    entityInstance: 4
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/TEMP_OUTLET_98
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
0x76:
    bExp: 0
    entityID: 7
    entityInstance: 5
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/TEMP_OUTLET_9A
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
0x77:
    bExp: 0
    entityID: 7
    entityInstance: 6
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/TEMP_OUTLET_9C
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC

0xA8:
    bExp: 0
    entityID: 3
    entityInstance: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/discrete/temperature/CPU_PROCHOT
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 3
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC


0xAF:
    bExp: 0
    entityID: 3
    entityInstance: 1
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/temperature/TEMP_PCH
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC


0xC1:
    bExp: 0
    entityID: 32
    entityInstance: 0
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 1
    offsetB: 0
    path: /xyz/openbmc_project/sensors/discrete/temperature/MEM_HOT
    rExp: 0
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 3
    sensorType: 1
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC



0xC4:
    bExp: 0
    entityID: 7
    entityInstance: 10
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 78
    offsetB: 0
    path: /xyz/openbmc_project/sensors/voltage/P3V3
    rExp: -3
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
0xC5:
    bExp: 0
    entityID: 7
    entityInstance: 12
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 78
    offsetB: 0
    path: /xyz/openbmc_project/sensors/voltage/P5V
    rExp: -3
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
0xCD:
    bExp: 0
    entityID: 7
    entityInstance: 15
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 78
    offsetB: 0
    path: /xyz/openbmc_project/sensors/voltage/P12V_STBY
    rExp: -3
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
0xD6:
    bExp: 0
    entityID: 7
    entityInstance: 14
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 78
    offsetB: 0
    path: /xyz/openbmc_project/sensors/voltage/P5V_STBY
    rExp: -3
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
0xD7:
    bExp: 0
    entityID: 7
    entityInstance: 11
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 78
    offsetB: 0
    path: /xyz/openbmc_project/sensors/voltage/P1V05_PCH_STBY
    rExp: -3
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
0xDE:
    bExp: 0
    entityID: 7
    entityInstance: 13
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 78
    offsetB: 0
    path: /xyz/openbmc_project/sensors/voltage/PVNN_PCH_STBY
    rExp: -3
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
0xDF:
    bExp: 0
    entityID: 7
    entityInstance: 8
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 78
    offsetB: 0
    path: /xyz/openbmc_project/sensors/voltage/P3V3_STBY
    rExp: -3
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
0xEB:
    bExp: 0
    entityID: 7
    entityInstance: 9
    interfaces:
        xyz.openbmc_project.Sensor.Value:
            Value:
                Offsets:
                    255:
                        type: int64_t
    multiplierM: 78
    offsetB: 0
    path: /xyz/openbmc_project/sensors/voltage/P3V_VBAT
    rExp: -3
    readingType: readingData
    scale: 0
    sensorNamePattern: nameLeaf
    sensorReadingType: 1
    sensorType: 2
    serviceInterface: org.freedesktop.DBus.Properties
    unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
